spring.application.name=worldcup-backend-2
# API Credentials
api.football.key=d38b1102022a61bf5b16ef203f1dba7a
api.football.url=https://v3.football.api-sports.io
# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/football_db
spring.datasource.username=shashi
spring.datasource.password=postgres

# JPA / Hibernate Settings
# Change from 'update' to 'create' just for one run
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



#security
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://securetoken.google.com/fifaoauth
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com